server:
  port: 8080

spring:
  application:
    name: ai-demo

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      base-url: https://dashscope.aliyuncs.com/compatible-mode/
      chat:
        options:
          model: qwen3.6-plus
          temperature: 0.7


app:
  auto-reply:
    enabled: true
    knowledge-base:
      profile-path: classpath:knowledge/profile.json
  browser-bot:
    chrome-path: /Applications/Google Chrome.app/Contents/MacOS/Google Chrome
    poll-interval-seconds: 3
    headless: false
